"""add_check_constraints

Revision ID: 63505e2817ac
Revises: a04bb93ae6eb
Create Date: 2026-08-28 13:57:37.579920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63505e2817ac'
down_revision: Union[str, Sequence[str], None] = 'a04bb93ae6eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('chk_payment_amount_positive', 'payments', 'amount >= 0')
    op.create_check_constraint('chk_recovery_case_amount_positive', 'recovery_cases', 'amount_at_risk >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_recovery_case_amount_positive', 'recovery_cases', type_='check')
    op.drop_constraint('chk_payment_amount_positive', 'payments', type_='check')
    # ### end Alembic commands ###
