"""Add payload to recovery_jobs

Revision ID: 906b317e5e85
Revises: 63505e2817ac
Create Date: 2026-09-02 09:20:10.862352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '906b317e5e85'
down_revision: Union[str, Sequence[str], None] = '63505e2817ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_jobs', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_jobs', 'payload')
    # ### end Alembic commands ###
