"""add_indexes_for_scaling

Revision ID: f649369deabb
Revises: 906b317e5e85
Create Date: 2026-09-02 17:24:47.457581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f649369deabb'
down_revision: Union[str, Sequence[str], None] = '906b317e5e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_recovery_attempts_case_id', 'recovery_attempts', ['recovery_case_id'], unique=False)
    op.create_index('ix_recovery_cases_created_at', 'recovery_cases', ['created_at'], unique=False)
    op.create_index('ix_recovery_decisions_case_id', 'recovery_decisions', ['recovery_case_id'], unique=False)
    op.create_index('ix_recovery_jobs_case_id', 'recovery_jobs', ['recovery_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recovery_jobs_case_id', table_name='recovery_jobs')
    op.drop_index('ix_recovery_decisions_case_id', table_name='recovery_decisions')
    op.drop_index('ix_recovery_cases_created_at', table_name='recovery_cases')
    op.drop_index('ix_recovery_attempts_case_id', table_name='recovery_attempts')
    # ### end Alembic commands ###
